- app/intentsChooser.html
- app/js/bus/api/intents/intentsApi.js
- app/js/bus/transport/participant.js
- app/js/bus/util/util.js
> Fixed Intents permissions & IE window.open

- app/js/debugger/common/visDirective.js
- app/js/debugger/metrics/metrics.js
- app/js/debugger/metrics/metrics.tpl.html
> feat(debugger): Metrics plotter now has a time frame.

- app/js/debugger/trafficSnooper/trafficSnooper.tpl.html
> feat(debugger): Updated Traffic Snooper UI.

- app/js/bus/api/system/systemApiApplicationValue.js
> fix(system.api): Remove circular reference in Application value.

- .jshintrc
- Gruntfile.js
- app/js/common/packetRouter.js
- test/lib/testTools.js
- test/tests/client-integration/specs/apis/systemApiSpec.js
- test/tests/unit/index.html
- test/tests/unit/specs/packetRouterSpec.js
> Feature packet router

- test/jasmine-iwc-html-reporter.css
- test/jasmine-iwc-html-reporter.js
- test/tests/bus-integration/index.html
- test/tests/client-integration/index.html
- test/tests/unit/index.html
> feat(jasmine): Migrated custom reporter to 2.2

- app/js/bus/api/system/systemApi.js
- test/tests/client-integration/specs/apis/systemApiSpec.js
> feat(legacy-support): Included widget GUID in system.api launch invocation

- .gitignore
- Gruntfile.js
- package.json
- packageRelease.sh
> chore(packaging): Add packaging scripts

- app/js/bus/util/log.js
> feat(log): removed use of bind

- app/css/debugger/debugger.css
> fix(debugger): ui-grid content should word-wrap rather than ellipsis.

- app/js/bus/api/endpoints.js
- app/js/defaultWiring.js
Removed duplicate endpoint root get.
> feat(endpoint): Added load failure catching (primarily for 404/401).

- app/js/common/util.js
- test/tests/unit/specs/utilSpec.js
> feat(util): Added query param adding utility.

- app/css/debugger/debugger.css
- app/js/bus/api/commonApiBase.js
- app/js/bus/api/locks/locksApi.js
- app/js/bus/api/locks/locksApiValue.js
- app/js/bus/transport/leaderGroupParticipant.js
- app/js/debugger/apis/apiDisplay.js
- app/js/debugger/general/general.tpl.html
- app/js/defaultWiring.js
- app/js/services/api/apiBase.js
- app/js/services/api/intents/intentsApi.js
- app/js/services/node/apiNode.js
- app/js/services/node/intents/IntentHandlerNode.js
- app/js/services/node/lifespan.js
feat(debugger): updated for lifespan.
feat(lifespan): can be set on node now.
> feat(locks): fixed prefetch issue.

- app/js/defaultWiring.js
feat(default wiring): Use prerender instead of hidden on visibility api for preventing prefetch.
> Default Wiring fix

- Gruntfile.js
- app/js/bus/transport/participant.js
- app/js/bus/transport/router.js
- app/js/bus/transport/routerWatchdogParticipant.js
- app/js/common/apiPromiseMixin.js
- app/js/services/api/apiBase.js
- app/js/services/api/names/namesApi.js
- app/js/services/api/system/systemApi.js
- test/tests/client-integration/specs/apis/systemApiSpec.js
- test/tests/client-integration/specs/clientSpec.js
- test/tests/unit/specs/services/apiBaseSpec.js
feat(bulkSend): Added for bulk send of packets (1 large packet of requests).
feat(names): Uses bulk send for heartbeats. refs #200
feat(apiPromiseMixin): fixed fixPacket for preConnection messages.
feat(System): intent registrations now use bulk send.
feat(TransportPacketContext): Added respondOn logic. refs #205
feat(tests): Added bulkSet/respondOn tests.
feat(routerWatchdogParticipant): heartbeats no longer receive a response.
> Performance enhancements.

- Gruntfile.js
> feat(grunt): Added a 204 response for PUT/POST/DELETE against the sample backend.

- app/js/services/api/apiBase.js
- demo/bouncingBalls/index.html
- demo/bouncingBalls/js/bouncingBalls.js
- demo/bouncingBalls/js/renderedBall.js
feat(demo): Fixed bouncing balls.
feat(apiBase): unwatch now checks for node existance.
> Bouncing balls Fix

- .travis.yml
> feat(Travis): Updated for new Travis build system.

- backend/server.js
feat(backend): Added Bower component routing for ozp-demo applications.
> Backend Routes

- Gruntfile.js
- app/debugger.html
- app/iframe_peer.html
- app/intentsChooser.html
- app/js/bus/api/apiFilters.js
- app/js/bus/api/apiNode.js
- app/js/services/node/data/dataNode.js
- backend/ServerConfig.js
- backend/server.js
feat(lifespan): Data Api Nodes now have Ephemeral lifespan if created with said property in its config.
feat(backend): Index page set to debugger.
feat(backend): Unit/Integration test bus removed from sample backend.
> Lifespan Configuration / Sample backend modifications

- app/js/services/api/intents/intentsApi.js
- app/js/services/node/intents/InflightIntentNode.js
feat(intents): Added deserialize state. Custom initialize data to handle inflight intents. #279
> Intent Inflight Node serialize Fix

- app/js/bus/util/ajaxPersistenceQueue.js
- test/tests/unit/specs/services/ajaxPersistenceQueueSpec.js
> feat(ajaxPersistenceQueue): Fixed Content-Type header config.

- backend/ServerConfig.js
- backend/lib/utils.js
- backend/routes/listing.js
- backend/server.js
feat(backend): Updated listing path generation & CORS configs to be more generalized for deployment.
> Backend Configuration

- app/js/bus/transport/postMessageParticipant.js
- app/js/client/client.js
- app/js/debugger/debugger.js
- app/js/defaultWiring.js
feat(Participant): Removed timeouts on Bus/Participants. Moved to a promise driven address assignment structure.
> Connection Init timeout removal

- app/js/client/client.js
- app/js/common/util.js
- app/js/defaultWiring.js
- app/js/services/node/lifespan.js
feat(visibility): util func should be common not bus bound.
refs #305
> feat(visibility): moved visibility api use to a utility function.

- Gruntfile.js
- package.json
> feat(Angular): Added angular wrapped libraries to build.

- app/js/bus/api/locks/locksApi.js
- app/js/bus/network/keyBroadcastLocalStorageLink.js
- app/js/bus/transport/postMessageParticipant.js
- app/js/bus/transport/router.js
- app/js/common/apiPromiseMixin.js
- app/js/common/packetRouter.js
- app/js/common/util.js
- app/js/defaultWiring.js
- app/js/services/api/intents/intentsApi.js
- app/js/services/api/system/systemApi.js
feat(logging): cleaned up ozpIwc.log calls.
feat(structuredClone): Disabled structured clone if ozpIwc.supportLegacy is true.
> Legacy Support & Log cleanups.

- app/js/bus/network/keyBroadcastLocalStorageLink.js
- app/js/bus/util/util.js
- backend/routes/listing.js
- backend/server.js
- bower.json
feat(localStorage): made IWC check for it's unique key and ignore other messages on localStorage.
feat(backend): Added legacy adapter to the sample backend.
refs #316
> IWC LocalStorage events & Back-end Legacy wrapping

- app/js/services/api/system/systemApi.js
- bower.json
- test/tests/unit/specs/services/system/systemApiSpec.js
fix(System.api): Launching inflightIntent resource no longer [object Object].
fix(System.api): Fixed Unit test for launching.
> Application Launching Fix.

- backend/server.js
> fix(backend): Fixed origin checking for CORS.

- .travis.yml
- app/js/bus/api/apiNode.js
- app/js/bus/transport/consensus/bully.js
- app/js/bus/transport/routerWatchdogParticipant.js
- app/js/services/api/data/dataApi.js
- app/js/services/node/data/dataNode.js
- app/js/services/node/lifespan.js
- test/tests/client-integration/specs/clientSpec.js
feat(lifespan): Added auto binding src address for bound lifespans.
feat(consensus): fixed a bully algorithm race condition.
fix(travis): checking npm versions.
feat(lifespan): added bound test for client.
refs #323
> Client use of bound lifespans & Bully race condition fix

- app/js/ozpIwc.loader.js
> fix(sharedWorker): Loader should relatively reference the bus code.

- app/js/client/client.js
- app/js/common/apiPromiseMixin.js
Fixes passing data with launching intents.
> feat(InFlightIntents): Altered ApiPromiseMixin to not resolve in flight intents when reaching the sending client.

- Gruntfile.js
- app/css/debugger/debugger.css
- app/debugger.html
- app/js/bus/transport/participant/debugger.js
- app/js/bus/transport/participant/postMessage.js
- app/js/bus/transport/participant/sharedWorker.js
- app/js/client/client.js
- app/js/client/debugger.js
- app/js/debugger/debugger.js
- app/js/debugger/general/general.js
- test/tests/client-integration/specs/clientSpec.js
feat(sharedWorker): Fixed browser race condition for shared worker initialization.
feat(debugger): Removed use of  and have direct client->debugger communication.
Added loading splash for debugger.
**TODO**: Debugger's traffic snooper & elections tab are inadvertently in a singleton control over packet logging, this is a bug and will be addressed in next release.
> Debugger SharedWorker Compliance & SharedWorker race condition fix.

- app/js/bus/transport/participant/debugger.js
fix(debugger): Packet logging moved into the debugger participant rather than statically handled.
mentioned in #342
> Debugger packet logging fix.

- app/js/debugger/debugger.js
> fix(debugger): default bus connection should be same URL dirpath as the debugger.html

- app/intentsChooser.html
- app/js/common/apiPromiseMixin.js
- app/js/services/api/intents/fsm.js
- app/js/services/api/system/api.js
- backend/routes/data.js
- backend/routes/index.js
feat(intents): application listing intent data now can drive opening an application to handle intent.
feat(intentChooser): now displays launching application option to handle intent."
feat(backend): sample backend now supplies templates needed to better determine content-type.
>  Intent updates

- app/js/bus/api/endpoints.js
> fix(data.api): fixed template generation that caused 405 puts on no backend.

- src/js/bus/api/locks/api.js
> Reduced initializing time for sharedworker browsers by forcing consensus.

- src/js/bus/api/services/intents/api.js
- src/js/bus/api/services/intents/routes.js
- src/js/common/apiPromiseMixin.js
- test/tests/unit/specs/api/intents/intentApiSpec.js
> Feat intent fix

- docs/iwc_guide/client/apis/intents/broadcast.md
- docs/iwc_guide/client/apis/intents/invoke.md
- docs/iwc_guide/client/apis/intents/register.md
- src/js/bus/api/services/intents/api.js
- src/js/bus/api/services/intents/routes.js
- src/js/common/apiPromiseMixin.js
> Added filtering/augmenting for broadcast promise resolution & callbacks

- src/js/client/client.js
- src/js/client/util/util.js
- test/tests/client-integration/specs/clientSpec.js
refs #363 
feat(Client): Updated Client params for sensibility.
feat(Client): Added tests for default connection.
> Updated ozpIwc.Client params

- components/debugger/css/debugger.css
- components/debugger/js/apis/apiDisplay.js
- components/debugger/js/apis/headerTemplate.tpl.html
- components/debugger/js/apis/resourceTemplate.tpl.html
- src/js/bus/api/base/api.js
- test/tests/client-integration/specs/apis/systemApiSpec.js
- test/tests/unit/specs/api/apiBaseSpec.js
#261 
feat(debugger):Updated api display for watch all.
fix(unwatch): Bug prevented removal from watchlist fixed.
fix(tests): blocked 2 system api client integration tests that are stale always fail (test needs rewrite).
> Debugger Update & Unwatch bug fix

- src/js/bus/api/services/intents/api.js
> Fix(intents): Open popup on invoker

- src/html/intentsChooser.html
- src/js/client/client.js
- src/js/client/util/util.js
#389 
Now a pulsed temporary overlay (click-through enabled).
Temporarily changes window title to notify as well (for tabs that aren't visible).
> feat(intents): Window and title notifications for intent choosing.

- Gruntfile.js
- NOTICE
- Readme.md
- components/debugger/js/general/about/genAbout.tpl.html
- docs/iwc_guide/FAQ.md
- docs/iwc_guide/README.md
- docs/iwc_guide/client/apis/intents/broadcast.md
- docs/iwc_guide/client/apis/intents/invoke.md
- docs/iwc_guide/client/apis/intents/overview.md
- docs/iwc_guide/client/apis/intents/register.md
- docs/iwc_guide/client/migration/pubsub_to_setwatch.md
- docs/iwc_guide/introduction/overview.md
- docs/iwc_guide/introduction/quickStart.md
- docs/iwc_guide/introduction/technologies.md
- src/js/bus/util/util.js
> refactor(widget): widget -> window/application
